#!/bin/sh
# docker-entrypoint.sh — runs before nginx starts inside the frontend container.
# Writes config.js with the value of the API_BASE env variable so the browser
# can find the API.  If API_BASE is empty, same-origin requests go through the
# nginx reverse-proxy that is also configured in this container.

set -e

CONFIG_FILE="/usr/share/nginx/html/config.js"

cat > "$CONFIG_FILE" <<EOF
// Auto-generated by docker-entrypoint.sh — do not edit manually.
window.__CONFIG__ = {
  API_BASE: '${API_BASE:-}'
};
EOF

echo "[entrypoint] config.js written (API_BASE='${API_BASE:-}')"

exec nginx -g 'daemon off;'
